# pipeline/vision.py
"""
v0.4 — Vision-enhanced figure descriptions.

Uses Gemma 4's multimodal capability to generate precise technical descriptions
of extracted PDF figures.  These descriptions are:
  1. Injected into the authoring prompt so the prose can accurately reference
     what each figure contains.
  2. Used as the image alt text in the blog post Markdown (better accessibility
     and search-engine indexing than raw PDF captions).

Results are cached in cache/<paper_id>_vision.json so the GPU work is never
repeated on re-runs.
"""
import json
import pathlib

from config import cfg
from llm import ask_with_image

# ── Prompt ───────────────────────────────────────────────────────────────────

_VISION_PROMPT = """\
This figure was extracted from a research paper. Analyze it carefully and \
write a precise 2-3 sentence technical description covering:
1. The figure type (e.g. architecture diagram, result plot, ablation table, \
qualitative visualization, comparison chart)
2. The key visual elements: axes labels, component names, data shown, or \
structural relationships depicted
3. What it demonstrates or proves about the paper's method or results

Write in present tense. Return ONLY the description — no preamble, \
no "This figure shows..." opener, no trailing commentary."""


# ── Public API ────────────────────────────────────────────────────────────────

def describe_figures(
    paper_id: str,
    figures: list[dict],
    processor,
    model,
) -> list[dict]:
    """
    Enrich each figure dict with a 'description' field generated by Gemma 4.

    Processes at most cfg.vision.max_figures figures (default 3) to bound
    the extra inference time.  Falls back gracefully: if vision fails for a
    figure, the field is left absent and author.py uses the PDF caption.

    Results cached in cache/<paper_id>_vision.json.
    """
    cache_file = pathlib.Path(f"cache/{paper_id}_vision.json")

    if cache_file.exists():
        print("  (cached) Skipping vision inference")
        _apply_cache(cache_file, figures, paper_id)
        return figures

    describable = _resolvable_figures(figures, paper_id)[: cfg.vision.max_figures]

    if not describable:
        print("  ⚠️  No resolvable figure paths — skipping vision")
        return figures

    cache_entries: list[dict] = []
    described = 0

    for fig, disk_path in describable:
        print(f"    🔭 Describing {disk_path.name}…")
        description = ask_with_image(
            prompt=_VISION_PROMPT,
            image_path=str(disk_path),
            processor=processor,
            model=model,
            temperature=0.1,
            max_new_tokens=300,
        )
        if description:
            fig["description"] = description
            cache_entries.append({
                "file": disk_path.name,
                "description": description,
            })
            described += 1

    print(f"  👁️  Vision: described {described}/{len(describable)} figures")

    if cache_entries:
        cache_file.parent.mkdir(exist_ok=True)
        cache_file.write_text(json.dumps(cache_entries, indent=2))

    return figures


# ── Helpers ───────────────────────────────────────────────────────────────────

def _resolvable_figures(
    figures: list[dict], paper_id: str
) -> list[tuple[dict, pathlib.Path]]:
    """Return (figure_dict, disk_path) pairs for figures that exist on disk."""
    result = []
    for fig in figures:
        raw_path = fig.get("path", "")
        if not raw_path:
            continue
        fname = pathlib.Path(raw_path).name
        # Stored path is relative to post URL (../../assets/…).
        # Actual file lives at docs/assets/figures/<paper_id>/<fname>.
        disk_path = pathlib.Path("docs/assets/figures") / paper_id / fname
        if disk_path.exists():
            result.append((fig, disk_path))
    return result


def _apply_cache(
    cache_file: pathlib.Path, figures: list[dict], paper_id: str
) -> None:
    """Merge previously cached descriptions back into figure dicts."""
    try:
        entries = json.loads(cache_file.read_text())
        desc_map = {e["file"]: e["description"] for e in entries}
        for fig in figures:
            fname = pathlib.Path(fig.get("path", "")).name
            if fname in desc_map:
                fig["description"] = desc_map[fname]
    except Exception:
        pass  # corrupted cache — silently skip; will re-run next time
